### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by arockenberger** [uio-library/hansteen-brev#2]
Hei!

I would really like to re-use the material here - but there is no license information.

I suggest choosing a license from (https://choosealicense.com/).

Best,

Annika

**Comment by superLine** [comment]
@danmichaelo  - this should be open domain. But we (as in I) should really refurbish the web-exibition explaining the project (https://www.ub.uio.no/fag/naturvitenskap-teknologi/astro/hansteen/index.html)

**Comment by danmichaelo** [comment]
Indeed! The reason I didn't add a LICENSE file was probably because the repo contains mixed materials. As for the scripts, I can license them freely. As for the catalogue, the original 1877 catalogue is now public domain. The remaining question then is if the database created during 2004/2005 digitization project is a derivative work (which adds new copyright) or just a faithful representation of the original catalogue (no additional copyright). My impression is that's it's more on the "faithful representation" side. Unfortunately there is no documentation from the project on this and we haven't been able to get in conctact with the persons involved with the creation of the database. *If* the database creation constitutes a derivative work, the next question is who's the copyright holder. If it's the university library (which I think it  might be since the project was organized by the library?), we can go ahead and make it public domain or CC-0. I will check with Rebecca what she thinks.

**Comment by danmichaelo** [comment]
Added a section in the README: https://github.com/uio-library/hansteen-brev#license and a LICENSE file. 

Thanks for bringing up this issue!
